<?php

/**
 * Implements hook_wysiwyg_plugin().
 *
 */
function ckeditor_template_generator_wysiwyg_plugin($editor, $version) {
    $plugins = array();
    switch ($editor) {
        case 'ckeditor':
            if ($version > 4) {
                $plugins['template_generator'] = array(
                    'path' => drupal_get_path('module', 'ckeditor_template_generator') . '/plugins/template_generator/',
                    'filename' => 'plugin.js',
                    'load' => TRUE,
                    'buttons' => array(
                        'template_generator' => t('Template Generator'),
                    ),
                );
            }
            break;
    }
    return $plugins;
}

